Docs for file
phootwork/phootwork.github.io pull request #18
Opened 2020-01-18 12:12 UTC by gossi

PR for #9 - mostly copy and paste from original docs with some adjustments needed for mkdocs.

2020-01-19 14:34 UTC, cristianoc72 requested changes
Great work! Very clear and meaningful as usual.
Just a couple of notes about markdown: the Python implementation is slightly different from Github flavoured (it also applies to me: I had written `*italic*` instead of `_italic_`).

2020-01-19 14:34 UTC, cristianoc72 commented on docs/collection.md
> -    - `ArrayList` - provides a List
In Python-Markdown, nested lists require 4 spaces (or 1 tab). See https://github.com/Python-Markdown/markdown/issues/3 discussion.

Same the following.

2020-01-19 14:34 UTC, cristianoc72 commented on docs/collection.md
> +Be careful: the parameters order is mandatory.
An admonition message must be indented with 4 spaces (or 1 tab) otherwise it's not included into the admonition but it's written on the next  line.

2020-01-19 14:34 UTC, cristianoc72 commented on docs/collection.md
> +Set doesn't have the [insert()](#addition_1) method.
Same: 4 spaces indentation for admonition.

2020-01-19 14:34 UTC, cristianoc72 commented on docs/collection.md
> +When you deal with Stack, the order is important: the constructor pushes the elements to end of the passed array,
Same.

2020-01-19 14:34 UTC, cristianoc72 commented on docs/collection.md
> +As for the Stack collection, when you deal with Queue, the order is important: the constructor enqueues the elements,
Same.

2020-01-19 14:34 UTC, cristianoc72 commented on docs/file.md
> +Note: `touch()` can also be used to changes `created` and `lastAcceessed` attributes.
Why not admonition?
```
!!! Note
    `touch()` can also be used to changes `created` and `lastAcceessed` attributes.
```

2020-01-31 18:48 UTC, gossi commented on docs/file.md
> +Note: `touch()` can also be used to changes `created` and `lastAcceessed` attributes.
great!

2020-01-31 18:50 UTC, gossi commented
Thanks, my auto-formatter thought this way it looks better 🙈 - Thanks for the review, did all the changes now.

2020-02-03 06:22 UTC, merged